### ISSUE TITLE
Handle creation prompt default to Y

### ISSUE THREAD

**Issue by GabrielBrandao1618** [EduardoRodriguesF/quartz#51]
When using `quartz use <non-existent-handle>` the CLI immediately figures there is no such handle and displays a prompt asking whether you would like to create one. In most of the CLI tools I use, the Y option is the default(`Y/n`), so I think it would be a good ideia implement this, since most of the time you actually want to create the handle anyways.

**Comment by EduardoRodriguesF** [comment]
What do you mean by "by default" exactly? If you'd provide an example application would be great too!

**Comment by GabrielBrandao1618** [comment]
> What do you mean by "by default" exactly? If you'd provide an example application would be great too!

So here is one example from Vtex CLI:
![image](https://github.com/user-attachments/assets/a3dac821-97e5-449b-8a6f-16c7e78fdb8f)
Notice that if I just hit Enter, it will create the workspace, that's what I mean by "default"
